/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho.pkg2.jogo.de.so;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author vinic
 */
public class JFrameTelaJogo extends javax.swing.JFrame {

    ArrayList<Tarefa> tarefas = new ArrayList<>();
    ArrayList<Integer> numtarefa= new ArrayList<>();
    
    ArrayList<Integer> mutex = new ArrayList<>();
    
    
    
    public JFrameTelaJogo() {
        initComponents();
        tarefas.add(GeradorTarefa.gerador());
        tarefas.add(GeradorTarefa.gerador());
        
        atualizarTarefas();
        
        for(int a=0;a<4;a++){
            numtarefa.add(null);
        }
        
        for(int a=0;a<10;a++){
            mutex.add(0);
        }
        
        jLabelTarefaExtra.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAlterarProcessoThread1 = new javax.swing.JButton();
        jButtonAlterarProcessoThread2 = new javax.swing.JButton();
        jButtonAlterarProcessoThread3 = new javax.swing.JButton();
        jButtonAlterarProcessoThread4 = new javax.swing.JButton();
        jLabelTextoProcessoAtual1 = new javax.swing.JLabel();
        jLabelTextoProcessoAtual2 = new javax.swing.JLabel();
        jLabelTextoProcessoAtual3 = new javax.swing.JLabel();
        jLabelTextoProcessoAtual4 = new javax.swing.JLabel();
        jLabelNomeThread1 = new javax.swing.JLabel();
        jLabelNomeThread2 = new javax.swing.JLabel();
        jLabelNomeThread3 = new javax.swing.JLabel();
        jLabelNomeThread4 = new javax.swing.JLabel();
        jLabelTextoUltimoProcesso1 = new javax.swing.JLabel();
        jLabelTextoUltimoProcesso2 = new javax.swing.JLabel();
        jLabelTextoPUltimoProcesso3 = new javax.swing.JLabel();
        jLabelTextoPUltimoProcesso4 = new javax.swing.JLabel();
        jLabelTextoMemoria = new javax.swing.JLabel();
        jLabelTextoEnderecoMemoria1 = new javax.swing.JLabel();
        jLabelTextoEnderecoMemoria2 = new javax.swing.JLabel();
        jLabelTextoEnderecoMemoria3 = new javax.swing.JLabel();
        jLabelTextoEnderecoMemoria4 = new javax.swing.JLabel();
        jLabelTextoEnderecoMemoria5 = new javax.swing.JLabel();
        jLabelTextoEnderecoMemoria6 = new javax.swing.JLabel();
        jLabelTextoEnderecoMemoria7 = new javax.swing.JLabel();
        jLabelTextoEnderecoMemoria8 = new javax.swing.JLabel();
        jLabelTextoEnderecoMemoria9 = new javax.swing.JLabel();
        jLabelTextoEnderecoMemoria10 = new javax.swing.JLabel();
        jLabelEndereçoMemoria0 = new javax.swing.JLabel();
        jLabelEndereçoMemoria1 = new javax.swing.JLabel();
        jLabelEndereçoMemoria2 = new javax.swing.JLabel();
        jLabelEndereçoMemoria3 = new javax.swing.JLabel();
        jLabelEndereçoMemoria4 = new javax.swing.JLabel();
        jLabelEndereçoMemoria5 = new javax.swing.JLabel();
        jLabelEndereçoMemoria6 = new javax.swing.JLabel();
        jLabelEndereçoMemoria7 = new javax.swing.JLabel();
        jLabelEndereçoMemoria8 = new javax.swing.JLabel();
        jLabelEndereçoMemoria9 = new javax.swing.JLabel();
        jLabelTextoInstrucaoProcesso1 = new javax.swing.JLabel();
        jLabelUltimoProcesso4 = new javax.swing.JLabel();
        jLabelNomeThread5 = new javax.swing.JLabel();
        jLabelInstrucaoProcesso1 = new javax.swing.JLabel();
        jLabelTextoNomeProcesso1 = new javax.swing.JLabel();
        jLabelNomeProcesso1 = new javax.swing.JLabel();
        jLabelTextoInstrucaoProcesso2 = new javax.swing.JLabel();
        jLabelNomeThread6 = new javax.swing.JLabel();
        jLabelInstrucaoProcesso2 = new javax.swing.JLabel();
        jLabelTextoNomeProcesso2 = new javax.swing.JLabel();
        jLabelNomeProcesso2 = new javax.swing.JLabel();
        jLabelTextoInstrucaoProcesso3 = new javax.swing.JLabel();
        jLabelNomeThread7 = new javax.swing.JLabel();
        jLabelInstrucaoProcesso3 = new javax.swing.JLabel();
        jLabelTextoNomeProcesso3 = new javax.swing.JLabel();
        jLabelNomeProcesso3 = new javax.swing.JLabel();
        jLabelTextoInstrucaoProcesso4 = new javax.swing.JLabel();
        jLabelNomeThread8 = new javax.swing.JLabel();
        jLabelInstrucaoProcesso4 = new javax.swing.JLabel();
        jLabelTextoNomeProcesso4 = new javax.swing.JLabel();
        jLabelNomeProcesso4 = new javax.swing.JLabel();
        jLabelTextoInstrucaoProcesso5 = new javax.swing.JLabel();
        jLabelNomeThread9 = new javax.swing.JLabel();
        jLabelInstrucaoProcesso5 = new javax.swing.JLabel();
        jLabelTextoNomeProcesso5 = new javax.swing.JLabel();
        jLabelNomeProcesso5 = new javax.swing.JLabel();
        jLabelTextoInstrucaoProcesso6 = new javax.swing.JLabel();
        jLabelNomeThread10 = new javax.swing.JLabel();
        jLabelInstrucaoProcesso6 = new javax.swing.JLabel();
        jLabelTextoNomeProcesso6 = new javax.swing.JLabel();
        jLabelNomeProcesso6 = new javax.swing.JLabel();
        jLabelTextoPrioridade4 = new javax.swing.JLabel();
        jLabelTextoPrioridade3 = new javax.swing.JLabel();
        jLabelTextoPrioridade5 = new javax.swing.JLabel();
        jLabelTextoPrioridade6 = new javax.swing.JLabel();
        jLabelPrioridade5 = new javax.swing.JLabel();
        jLabelPrioridade6 = new javax.swing.JLabel();
        jLabelBorda1 = new javax.swing.JLabel();
        jLabelBorda2 = new javax.swing.JLabel();
        jLabelBorda3 = new javax.swing.JLabel();
        jLabelBorda4 = new javax.swing.JLabel();
        jLabelBorda5 = new javax.swing.JLabel();
        jLabelBorda6 = new javax.swing.JLabel();
        jLabelBorda7 = new javax.swing.JLabel();
        jLabelBorda8 = new javax.swing.JLabel();
        jLabelBorda9 = new javax.swing.JLabel();
        jLabelBorda10 = new javax.swing.JLabel();
        jLabelTextoPrioridade2 = new javax.swing.JLabel();
        jLabelTextoPrioridade1 = new javax.swing.JLabel();
        jLabelPrioridade3 = new javax.swing.JLabel();
        jLabelPrioridade4 = new javax.swing.JLabel();
        jLabelPrioridade2 = new javax.swing.JLabel();
        jLabelPrioridade1 = new javax.swing.JLabel();
        jLabelprocessoatual1 = new javax.swing.JLabel();
        jLabelprocessoatual2 = new javax.swing.JLabel();
        jLabelprocessoatual3 = new javax.swing.JLabel();
        jLabelprocessoatual4 = new javax.swing.JLabel();
        jButtonIniciarProcessamento = new javax.swing.JButton();
        jLabelTarefaExtra = new javax.swing.JLabel();
        jLabelUltimoProcesso1 = new javax.swing.JLabel();
        jLabelUltimoProcesso2 = new javax.swing.JLabel();
        jLabelUltimoProcesso3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonAlterarProcessoThread1.setText("Alterar o Processo");
        jButtonAlterarProcessoThread1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarProcessoThread1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterarProcessoThread1);
        jButtonAlterarProcessoThread1.setBounds(30, 280, 260, 50);

        jButtonAlterarProcessoThread2.setText("Alterar o Processo");
        jButtonAlterarProcessoThread2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarProcessoThread2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterarProcessoThread2);
        jButtonAlterarProcessoThread2.setBounds(330, 280, 260, 50);

        jButtonAlterarProcessoThread3.setText("Alterar o Processo");
        jButtonAlterarProcessoThread3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarProcessoThread3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterarProcessoThread3);
        jButtonAlterarProcessoThread3.setBounds(630, 280, 260, 50);

        jButtonAlterarProcessoThread4.setText("Alterar o Processo");
        jButtonAlterarProcessoThread4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarProcessoThread4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterarProcessoThread4);
        jButtonAlterarProcessoThread4.setBounds(930, 280, 260, 50);

        jLabelTextoProcessoAtual1.setText("Processo Atual:");
        getContentPane().add(jLabelTextoProcessoAtual1);
        jLabelTextoProcessoAtual1.setBounds(40, 190, 250, 14);

        jLabelTextoProcessoAtual2.setText("Processo Atual:");
        getContentPane().add(jLabelTextoProcessoAtual2);
        jLabelTextoProcessoAtual2.setBounds(340, 190, 250, 14);

        jLabelTextoProcessoAtual3.setText("Processo Atual:");
        getContentPane().add(jLabelTextoProcessoAtual3);
        jLabelTextoProcessoAtual3.setBounds(640, 190, 250, 14);

        jLabelTextoProcessoAtual4.setText("Processo Atual:");
        getContentPane().add(jLabelTextoProcessoAtual4);
        jLabelTextoProcessoAtual4.setBounds(940, 190, 250, 14);

        jLabelNomeThread1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomeThread1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeThread1.setText("Thread 1");
        jLabelNomeThread1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelNomeThread1);
        jLabelNomeThread1.setBounds(30, 40, 260, 50);

        jLabelNomeThread2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomeThread2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeThread2.setText("Thread 2");
        jLabelNomeThread2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelNomeThread2);
        jLabelNomeThread2.setBounds(330, 40, 260, 50);

        jLabelNomeThread3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomeThread3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeThread3.setText("Thread 3");
        jLabelNomeThread3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelNomeThread3);
        jLabelNomeThread3.setBounds(630, 40, 260, 50);

        jLabelNomeThread4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomeThread4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeThread4.setText("Thread 4");
        jLabelNomeThread4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelNomeThread4);
        jLabelNomeThread4.setBounds(930, 40, 260, 50);

        jLabelTextoUltimoProcesso1.setText("Ultimo Processo:");
        getContentPane().add(jLabelTextoUltimoProcesso1);
        jLabelTextoUltimoProcesso1.setBounds(40, 100, 250, 14);

        jLabelTextoUltimoProcesso2.setText("Ultimo Processo:");
        getContentPane().add(jLabelTextoUltimoProcesso2);
        jLabelTextoUltimoProcesso2.setBounds(340, 100, 250, 14);

        jLabelTextoPUltimoProcesso3.setText("Ultimo Processo:");
        getContentPane().add(jLabelTextoPUltimoProcesso3);
        jLabelTextoPUltimoProcesso3.setBounds(640, 100, 250, 14);

        jLabelTextoPUltimoProcesso4.setText("Ultimo Processo:");
        getContentPane().add(jLabelTextoPUltimoProcesso4);
        jLabelTextoPUltimoProcesso4.setBounds(940, 100, 250, 14);

        jLabelTextoMemoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoMemoria.setText("Memoria");
        jLabelTextoMemoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelTextoMemoria);
        jLabelTextoMemoria.setBounds(220, 390, 70, 30);

        jLabelTextoEnderecoMemoria1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoEnderecoMemoria1.setText("0");
        jLabelTextoEnderecoMemoria1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelTextoEnderecoMemoria1);
        jLabelTextoEnderecoMemoria1.setBounds(290, 390, 70, 30);

        jLabelTextoEnderecoMemoria2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoEnderecoMemoria2.setText("1");
        jLabelTextoEnderecoMemoria2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelTextoEnderecoMemoria2);
        jLabelTextoEnderecoMemoria2.setBounds(360, 390, 70, 30);

        jLabelTextoEnderecoMemoria3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoEnderecoMemoria3.setText("2");
        jLabelTextoEnderecoMemoria3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelTextoEnderecoMemoria3);
        jLabelTextoEnderecoMemoria3.setBounds(430, 390, 70, 30);

        jLabelTextoEnderecoMemoria4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoEnderecoMemoria4.setText("3");
        jLabelTextoEnderecoMemoria4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelTextoEnderecoMemoria4);
        jLabelTextoEnderecoMemoria4.setBounds(500, 390, 70, 30);

        jLabelTextoEnderecoMemoria5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoEnderecoMemoria5.setText("4");
        jLabelTextoEnderecoMemoria5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelTextoEnderecoMemoria5);
        jLabelTextoEnderecoMemoria5.setBounds(570, 390, 70, 30);

        jLabelTextoEnderecoMemoria6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoEnderecoMemoria6.setText("5");
        jLabelTextoEnderecoMemoria6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelTextoEnderecoMemoria6);
        jLabelTextoEnderecoMemoria6.setBounds(640, 390, 70, 30);

        jLabelTextoEnderecoMemoria7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoEnderecoMemoria7.setText("6");
        jLabelTextoEnderecoMemoria7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelTextoEnderecoMemoria7);
        jLabelTextoEnderecoMemoria7.setBounds(710, 390, 70, 30);

        jLabelTextoEnderecoMemoria8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoEnderecoMemoria8.setText("7");
        jLabelTextoEnderecoMemoria8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelTextoEnderecoMemoria8);
        jLabelTextoEnderecoMemoria8.setBounds(780, 390, 70, 30);

        jLabelTextoEnderecoMemoria9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoEnderecoMemoria9.setText("8");
        jLabelTextoEnderecoMemoria9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelTextoEnderecoMemoria9);
        jLabelTextoEnderecoMemoria9.setBounds(850, 390, 70, 30);

        jLabelTextoEnderecoMemoria10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextoEnderecoMemoria10.setText("9");
        jLabelTextoEnderecoMemoria10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelTextoEnderecoMemoria10);
        jLabelTextoEnderecoMemoria10.setBounds(920, 390, 70, 30);

        jLabelEndereçoMemoria0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEndereçoMemoria0.setText("0");
        jLabelEndereçoMemoria0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelEndereçoMemoria0);
        jLabelEndereçoMemoria0.setBounds(290, 420, 70, 30);

        jLabelEndereçoMemoria1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEndereçoMemoria1.setText("0");
        jLabelEndereçoMemoria1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelEndereçoMemoria1);
        jLabelEndereçoMemoria1.setBounds(360, 420, 70, 30);

        jLabelEndereçoMemoria2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEndereçoMemoria2.setText("0");
        jLabelEndereçoMemoria2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelEndereçoMemoria2);
        jLabelEndereçoMemoria2.setBounds(430, 420, 70, 30);

        jLabelEndereçoMemoria3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEndereçoMemoria3.setText("0");
        jLabelEndereçoMemoria3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelEndereçoMemoria3);
        jLabelEndereçoMemoria3.setBounds(500, 420, 70, 30);

        jLabelEndereçoMemoria4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEndereçoMemoria4.setText("0");
        jLabelEndereçoMemoria4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelEndereçoMemoria4);
        jLabelEndereçoMemoria4.setBounds(570, 420, 70, 30);

        jLabelEndereçoMemoria5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEndereçoMemoria5.setText("0");
        jLabelEndereçoMemoria5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelEndereçoMemoria5);
        jLabelEndereçoMemoria5.setBounds(640, 420, 70, 30);

        jLabelEndereçoMemoria6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEndereçoMemoria6.setText("0");
        jLabelEndereçoMemoria6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelEndereçoMemoria6);
        jLabelEndereçoMemoria6.setBounds(710, 420, 70, 30);

        jLabelEndereçoMemoria7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEndereçoMemoria7.setText("0");
        jLabelEndereçoMemoria7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelEndereçoMemoria7);
        jLabelEndereçoMemoria7.setBounds(780, 420, 70, 30);

        jLabelEndereçoMemoria8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEndereçoMemoria8.setText("0");
        jLabelEndereçoMemoria8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelEndereçoMemoria8);
        jLabelEndereçoMemoria8.setBounds(850, 420, 70, 30);

        jLabelEndereçoMemoria9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEndereçoMemoria9.setText("0");
        jLabelEndereçoMemoria9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelEndereçoMemoria9);
        jLabelEndereçoMemoria9.setBounds(920, 420, 70, 30);

        jLabelTextoInstrucaoProcesso1.setText("Instruções do Processo:");
        getContentPane().add(jLabelTextoInstrucaoProcesso1);
        jLabelTextoInstrucaoProcesso1.setBounds(40, 610, 160, 14);
        getContentPane().add(jLabelUltimoProcesso4);
        jLabelUltimoProcesso4.setBounds(960, 130, 230, 30);

        jLabelNomeThread5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomeThread5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeThread5.setText("Processo 1");
        jLabelNomeThread5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelNomeThread5);
        jLabelNomeThread5.setBounds(30, 510, 260, 50);
        getContentPane().add(jLabelInstrucaoProcesso1);
        jLabelInstrucaoProcesso1.setBounds(40, 630, 250, 20);

        jLabelTextoNomeProcesso1.setText("Nome do Processo:");
        getContentPane().add(jLabelTextoNomeProcesso1);
        jLabelTextoNomeProcesso1.setBounds(40, 570, 250, 14);
        getContentPane().add(jLabelNomeProcesso1);
        jLabelNomeProcesso1.setBounds(40, 590, 250, 20);

        jLabelTextoInstrucaoProcesso2.setText("Instruções do Processo:");
        getContentPane().add(jLabelTextoInstrucaoProcesso2);
        jLabelTextoInstrucaoProcesso2.setBounds(40, 780, 160, 14);

        jLabelNomeThread6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomeThread6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeThread6.setText("Processo 2");
        jLabelNomeThread6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelNomeThread6);
        jLabelNomeThread6.setBounds(30, 680, 260, 50);
        getContentPane().add(jLabelInstrucaoProcesso2);
        jLabelInstrucaoProcesso2.setBounds(40, 800, 250, 20);

        jLabelTextoNomeProcesso2.setText("Nome do Processo:");
        getContentPane().add(jLabelTextoNomeProcesso2);
        jLabelTextoNomeProcesso2.setBounds(40, 740, 250, 14);
        getContentPane().add(jLabelNomeProcesso2);
        jLabelNomeProcesso2.setBounds(40, 760, 250, 20);

        jLabelTextoInstrucaoProcesso3.setText("Instruções do Processo:");
        getContentPane().add(jLabelTextoInstrucaoProcesso3);
        jLabelTextoInstrucaoProcesso3.setBounds(320, 610, 160, 14);

        jLabelNomeThread7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomeThread7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeThread7.setText("Processo 3");
        jLabelNomeThread7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelNomeThread7);
        jLabelNomeThread7.setBounds(310, 510, 260, 50);
        getContentPane().add(jLabelInstrucaoProcesso3);
        jLabelInstrucaoProcesso3.setBounds(320, 630, 250, 20);

        jLabelTextoNomeProcesso3.setText("Nome do Processo:");
        getContentPane().add(jLabelTextoNomeProcesso3);
        jLabelTextoNomeProcesso3.setBounds(320, 570, 130, 14);
        getContentPane().add(jLabelNomeProcesso3);
        jLabelNomeProcesso3.setBounds(320, 590, 250, 20);

        jLabelTextoInstrucaoProcesso4.setText("Instruções do Processo:");
        getContentPane().add(jLabelTextoInstrucaoProcesso4);
        jLabelTextoInstrucaoProcesso4.setBounds(320, 780, 160, 14);

        jLabelNomeThread8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomeThread8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeThread8.setText("Processo 4");
        jLabelNomeThread8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelNomeThread8);
        jLabelNomeThread8.setBounds(310, 680, 260, 50);
        getContentPane().add(jLabelInstrucaoProcesso4);
        jLabelInstrucaoProcesso4.setBounds(320, 800, 250, 20);

        jLabelTextoNomeProcesso4.setText("Nome do Processo:");
        getContentPane().add(jLabelTextoNomeProcesso4);
        jLabelTextoNomeProcesso4.setBounds(320, 740, 140, 14);
        getContentPane().add(jLabelNomeProcesso4);
        jLabelNomeProcesso4.setBounds(320, 760, 250, 20);

        jLabelTextoInstrucaoProcesso5.setText("Instruções do Processo:");
        getContentPane().add(jLabelTextoInstrucaoProcesso5);
        jLabelTextoInstrucaoProcesso5.setBounds(600, 610, 160, 14);

        jLabelNomeThread9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomeThread9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeThread9.setText("Processo 5");
        jLabelNomeThread9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelNomeThread9);
        jLabelNomeThread9.setBounds(590, 510, 260, 50);
        getContentPane().add(jLabelInstrucaoProcesso5);
        jLabelInstrucaoProcesso5.setBounds(600, 630, 250, 20);

        jLabelTextoNomeProcesso5.setText("Nome do Processo:");
        getContentPane().add(jLabelTextoNomeProcesso5);
        jLabelTextoNomeProcesso5.setBounds(600, 570, 150, 14);
        getContentPane().add(jLabelNomeProcesso5);
        jLabelNomeProcesso5.setBounds(600, 590, 250, 20);

        jLabelTextoInstrucaoProcesso6.setText("Instruções do Processo:");
        getContentPane().add(jLabelTextoInstrucaoProcesso6);
        jLabelTextoInstrucaoProcesso6.setBounds(600, 780, 160, 14);

        jLabelNomeThread10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomeThread10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeThread10.setText("Processo 6");
        jLabelNomeThread10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelNomeThread10);
        jLabelNomeThread10.setBounds(590, 680, 260, 50);
        getContentPane().add(jLabelInstrucaoProcesso6);
        jLabelInstrucaoProcesso6.setBounds(600, 800, 250, 20);

        jLabelTextoNomeProcesso6.setText("Nome do Processo:");
        getContentPane().add(jLabelTextoNomeProcesso6);
        jLabelTextoNomeProcesso6.setBounds(600, 740, 250, 14);
        getContentPane().add(jLabelNomeProcesso6);
        jLabelNomeProcesso6.setBounds(600, 760, 250, 20);

        jLabelTextoPrioridade4.setText("Prioridade");
        getContentPane().add(jLabelTextoPrioridade4);
        jLabelTextoPrioridade4.setBounds(510, 740, 60, 14);

        jLabelTextoPrioridade3.setText("Prioridade");
        getContentPane().add(jLabelTextoPrioridade3);
        jLabelTextoPrioridade3.setBounds(510, 570, 60, 14);

        jLabelTextoPrioridade5.setText("Prioridade");
        getContentPane().add(jLabelTextoPrioridade5);
        jLabelTextoPrioridade5.setBounds(790, 570, 60, 14);

        jLabelTextoPrioridade6.setText("Prioridade");
        getContentPane().add(jLabelTextoPrioridade6);
        jLabelTextoPrioridade6.setBounds(790, 740, 60, 14);
        getContentPane().add(jLabelPrioridade5);
        jLabelPrioridade5.setBounds(790, 580, 60, 20);
        getContentPane().add(jLabelPrioridade6);
        jLabelPrioridade6.setBounds(790, 750, 60, 20);

        jLabelBorda1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelBorda1);
        jLabelBorda1.setBounds(30, 40, 260, 290);

        jLabelBorda2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelBorda2);
        jLabelBorda2.setBounds(330, 40, 260, 290);

        jLabelBorda3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelBorda3);
        jLabelBorda3.setBounds(630, 40, 260, 290);

        jLabelBorda4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelBorda4);
        jLabelBorda4.setBounds(930, 40, 260, 290);

        jLabelBorda5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelBorda5);
        jLabelBorda5.setBounds(30, 510, 260, 150);

        jLabelBorda6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelBorda6);
        jLabelBorda6.setBounds(30, 680, 260, 150);

        jLabelBorda7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelBorda7);
        jLabelBorda7.setBounds(310, 510, 260, 150);

        jLabelBorda8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelBorda8);
        jLabelBorda8.setBounds(310, 680, 260, 150);

        jLabelBorda9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelBorda9);
        jLabelBorda9.setBounds(590, 510, 260, 150);

        jLabelBorda10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabelBorda10);
        jLabelBorda10.setBounds(590, 680, 260, 150);

        jLabelTextoPrioridade2.setText("Prioridade");
        getContentPane().add(jLabelTextoPrioridade2);
        jLabelTextoPrioridade2.setBounds(230, 740, 60, 14);

        jLabelTextoPrioridade1.setText("Prioridade");
        getContentPane().add(jLabelTextoPrioridade1);
        jLabelTextoPrioridade1.setBounds(230, 570, 60, 14);
        getContentPane().add(jLabelPrioridade3);
        jLabelPrioridade3.setBounds(510, 580, 60, 20);
        getContentPane().add(jLabelPrioridade4);
        jLabelPrioridade4.setBounds(510, 750, 60, 20);
        getContentPane().add(jLabelPrioridade2);
        jLabelPrioridade2.setBounds(230, 750, 60, 20);
        getContentPane().add(jLabelPrioridade1);
        jLabelPrioridade1.setBounds(230, 580, 60, 20);
        getContentPane().add(jLabelprocessoatual1);
        jLabelprocessoatual1.setBounds(50, 210, 240, 40);
        getContentPane().add(jLabelprocessoatual2);
        jLabelprocessoatual2.setBounds(350, 210, 240, 40);
        getContentPane().add(jLabelprocessoatual3);
        jLabelprocessoatual3.setBounds(650, 210, 220, 40);
        getContentPane().add(jLabelprocessoatual4);
        jLabelprocessoatual4.setBounds(970, 210, 220, 40);

        jButtonIniciarProcessamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonIniciarProcessamento.setText("Executar uma vez.");
        jButtonIniciarProcessamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarProcessamentoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIniciarProcessamento);
        jButtonIniciarProcessamento.setBounds(910, 680, 240, 150);

        jLabelTarefaExtra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTarefaExtra.setText("Existe processos em espera.");
        jLabelTarefaExtra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabelTarefaExtra);
        jLabelTarefaExtra.setBounds(910, 510, 240, 150);
        getContentPane().add(jLabelUltimoProcesso1);
        jLabelUltimoProcesso1.setBounds(60, 130, 230, 30);
        getContentPane().add(jLabelUltimoProcesso2);
        jLabelUltimoProcesso2.setBounds(360, 130, 230, 30);
        getContentPane().add(jLabelUltimoProcesso3);
        jLabelUltimoProcesso3.setBounds(660, 130, 230, 30);

        setSize(new java.awt.Dimension(1266, 929));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarProcessoThread1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarProcessoThread1ActionPerformed
       Integer num;
       num = Integer.parseInt(JOptionPane.showInputDialog("Digite uma tarefa de 1 a 6 para executar na Threads 1.", ""));
       
       if(num==1||num==2||num==3||num==4||num==5||num==6){
           num--;
            numtarefa.set(0, num);
            if(numtarefa.get(1)==num){
                numtarefa.set(1, null);
            }
            if (numtarefa.get(2)==num) {
                numtarefa.set(2, null);
            }
            if(numtarefa.get(3)==num){
                numtarefa.set(3, null);
            }
        }
       else{
           JOptionPane.showMessageDialog(null, "Entrada invalida");
       }
       atualizarthreadtextoatual();
       
    }//GEN-LAST:event_jButtonAlterarProcessoThread1ActionPerformed
          
    private void jButtonAlterarProcessoThread2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarProcessoThread2ActionPerformed
      Integer num;
        
            num = Integer.parseInt(JOptionPane.showInputDialog("Digite uma tarefa de 1 a 6 para executar na Threads 2.", ""));
       
                if(num==1||num==2||num==3||num==4||num==5||num==6){
                    num--;
                    numtarefa.set(1, num);
                    if(numtarefa.get(0)==num){
                        numtarefa.set(0, null);
                    }
                    if (numtarefa.get(2)==num) {
                        numtarefa.set(2, null);
                    }
                    if(numtarefa.get(3)==num){
                        numtarefa.set(3, null);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Entrada invalida");
                }
        atualizarthreadtextoatual();
    }//GEN-LAST:event_jButtonAlterarProcessoThread2ActionPerformed

    private void jButtonAlterarProcessoThread3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarProcessoThread3ActionPerformed
        Integer num;
        
            num = Integer.parseInt(JOptionPane.showInputDialog("Digite uma tarefa de 1 a 6 para executar na Threads 3.", ""));
       
                if(num==1||num==2||num==3||num==4||num==5||num==6){
                    num--;
                    numtarefa.set(2, num);
                    if(numtarefa.get(0)==num){
                        numtarefa.set(0, null);
                    }
                    if (numtarefa.get(1)==num) {
                        numtarefa.set(1, null);
                    }
                    if(numtarefa.get(3)==num){
                        numtarefa.set(3, null);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Entrada invalida");
                }
        atualizarthreadtextoatual();
    }//GEN-LAST:event_jButtonAlterarProcessoThread3ActionPerformed

    private void jButtonAlterarProcessoThread4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarProcessoThread4ActionPerformed
        Integer num;
        
            num = Integer.parseInt(JOptionPane.showInputDialog("Digite uma tarefa de 1 a 6 para executar na Threads 4.", ""));
       
                if(num==1||num==2||num==3||num==4||num==5||num==6){
                    num--;
                    numtarefa.set(3, num);
                    if(numtarefa.get(0)==num){
                        numtarefa.set(0, null);
                    }
                    if (numtarefa.get(1)==num) {
                        numtarefa.set(1, null);
                    }
                    if(numtarefa.get(2)==num){
                        numtarefa.set(2, null);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Entrada invalida");
                }
        atualizarthreadtextoatual();
    }//GEN-LAST:event_jButtonAlterarProcessoThread4ActionPerformed

    private void jButtonIniciarProcessamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarProcessamentoActionPerformed
       
        System.out.println(numtarefa);
        if(numtarefa.get(0)==null){
            JOptionPane.showMessageDialog(null, "A Thread 1 não executou nada.");     
        }
        else{
            Thread thread1 = new Thread(tarefas.get(numtarefa.get(0)), this, 1);
            thread1.compute();
        }
        System.out.println(numtarefa);
        if(numtarefa.get(1)==null){
            JOptionPane.showMessageDialog(null, "A Thread 2 não executou nada.");     
        }
        else{
            Thread thread2 = new Thread(tarefas.get(numtarefa.get(1)), this, 2);
            thread2.compute();
        }
        
        if(numtarefa.get(2)==null){
            JOptionPane.showMessageDialog(null, "A Thread 3 não executou nada.");     
        }
        else{
            Thread thread3 = new Thread(tarefas.get(numtarefa.get(2)), this, 3);
            thread3.compute();
        }
        
        if(numtarefa.get(3)==null){
            JOptionPane.showMessageDialog(null, "A Thread 4 não executou nada.");     
        }
        else{
            Thread thread4 = new Thread(tarefas.get(numtarefa.get(3)), this, 4);
            thread4.compute();
        }
        
        Random generator = new Random();
        int ale = generator.nextInt(5);
        if(ale==1){
            tarefas.add(GeradorTarefa.gerador());           
        }       
               
        arrumar();
    }//GEN-LAST:event_jButtonIniciarProcessamentoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTelaJogo().setVisible(true);
            }
        });
    }
    
    public void atualizarthreadtextoatual(){
    
        
        if (numtarefa.get(0)!=null) {
          jLabelprocessoatual1.setText(tarefas.get(numtarefa.get(0)).nome);  
        }
        
        if (numtarefa.get(1)!=null) {
          jLabelprocessoatual2.setText(tarefas.get(numtarefa.get(1)).nome); 
        }
        
        if (numtarefa.get(2)!=null) {
          jLabelprocessoatual3.setText(tarefas.get(numtarefa.get(2)).nome);
        }
        
        if (numtarefa.get(3)!=null) {
          jLabelprocessoatual4.setText(tarefas.get(numtarefa.get(3)).nome);
        }
    }
    
    public void atualizarthreadtextoultimoprocesso(){
        jLabelUltimoProcesso1.setText("");
        jLabelUltimoProcesso2.setText("");
        jLabelUltimoProcesso3.setText("");
        jLabelUltimoProcesso4.setText("");
        
        jLabelUltimoProcesso1.setText(jLabelprocessoatual1.getText());
        jLabelprocessoatual1.setText("");
        jLabelUltimoProcesso2.setText(jLabelprocessoatual2.getText());
        jLabelprocessoatual2.setText("");
        jLabelUltimoProcesso3.setText(jLabelprocessoatual3.getText());
        jLabelprocessoatual3.setText("");
        jLabelUltimoProcesso4.setText(jLabelprocessoatual4.getText());
        jLabelprocessoatual4.setText("");
        
        
        
    }
    
    public void atualizarTarefas(){
        
            limparprocessosarraylist();
            
            limparjftarefas();
        
            jLabelNomeProcesso1.setText(tarefas.get(0).nome);
            jLabelPrioridade1.setText(String.valueOf(tarefas.get(0).prioridade));
            for (int i = 0; i < tarefas.get(0).operação.size(); i++) {
                jLabelInstrucaoProcesso1.setText(jLabelInstrucaoProcesso1.getText()+" "+tarefas.get(0).operação.get(i));
            }
            
            if (tarefas.size()>1) {
            jLabelNomeProcesso2.setText(tarefas.get(1).nome);
            jLabelPrioridade2.setText(String.valueOf(tarefas.get(1).prioridade));
            for (int i = 0; i < tarefas.get(1).operação.size(); i++) {
                jLabelInstrucaoProcesso2.setText(jLabelInstrucaoProcesso2.getText()+" "+tarefas.get(1).operação.get(i));
            }
            }
            
            if (tarefas.size()>2) {
            jLabelNomeProcesso3.setText(tarefas.get(2).nome);
            jLabelPrioridade3.setText(String.valueOf(tarefas.get(2).prioridade));
            for (int i = 0; i < tarefas.get(2).operação.size(); i++) {
                jLabelInstrucaoProcesso3.setText(jLabelInstrucaoProcesso3.getText()+" "+tarefas.get(2).operação.get(i));
            }
            }
            
            
             if (tarefas.size()>3) {
            jLabelNomeProcesso4.setText(tarefas.get(3).nome);
            jLabelPrioridade4.setText(String.valueOf(tarefas.get(3).prioridade));
            for (int i = 0; i < tarefas.get(3).operação.size(); i++) {
                jLabelInstrucaoProcesso4.setText(jLabelInstrucaoProcesso4.getText()+" "+tarefas.get(3).operação.get(i));
            }
            }
             
            if (tarefas.size()>4) {
            jLabelNomeProcesso5.setText(tarefas.get(4).nome);
            jLabelPrioridade5.setText(String.valueOf(tarefas.get(4).prioridade));
            for (int i = 0; i < tarefas.get(4).operação.size(); i++) {
                jLabelInstrucaoProcesso5.setText(jLabelInstrucaoProcesso5.getText()+" "+tarefas.get(4).operação.get(i));
            }
            } 
            
            if (tarefas.size()>5) {
            jLabelNomeProcesso6.setText(tarefas.get(5).nome);
            jLabelPrioridade6.setText(String.valueOf(tarefas.get(5).prioridade));
            for (int i = 0; i < tarefas.get(5).operação.size(); i++) {
                jLabelInstrucaoProcesso6.setText(jLabelInstrucaoProcesso6.getText()+" "+tarefas.get(5).operação.get(i));
            }
            }
        
    }
    
    public void arrumaralocacao(){
        jLabelEndereçoMemoria0.setText(String.valueOf(mutex.get(0)));
        jLabelEndereçoMemoria1.setText(String.valueOf(mutex.get(1)));
        jLabelEndereçoMemoria2.setText(String.valueOf(mutex.get(2)));
        jLabelEndereçoMemoria3.setText(String.valueOf(mutex.get(3)));
        jLabelEndereçoMemoria4.setText(String.valueOf(mutex.get(4)));
        jLabelEndereçoMemoria5.setText(String.valueOf(mutex.get(5)));
        jLabelEndereçoMemoria6.setText(String.valueOf(mutex.get(6)));
        jLabelEndereçoMemoria7.setText(String.valueOf(mutex.get(7)));
        jLabelEndereçoMemoria8.setText(String.valueOf(mutex.get(8)));
        jLabelEndereçoMemoria9.setText(String.valueOf(mutex.get(9)));
        
    }
    
    public void limparprocessosarraylist(){
        for (int i = 0; i < tarefas.size(); i++) {
            if(tarefas.get(i).operação.size()==0){
                tarefas.remove(i);
                i=0;
            }
        }
    }
            
    public void limparjftarefas(){
        
        jLabelNomeProcesso1.setText("");
        jLabelPrioridade1.setText("");
        jLabelInstrucaoProcesso1.setText("");
        jLabelNomeProcesso2.setText("");
        jLabelPrioridade2.setText("");
        jLabelInstrucaoProcesso2.setText("");
        jLabelNomeProcesso3.setText("");
        jLabelPrioridade3.setText("");
        jLabelInstrucaoProcesso3.setText("");
        jLabelNomeProcesso4.setText("");
        jLabelPrioridade4.setText("");
        jLabelInstrucaoProcesso4.setText("");
        jLabelNomeProcesso5.setText("");
        jLabelPrioridade5.setText("");
        jLabelInstrucaoProcesso5.setText("");
        jLabelNomeProcesso6.setText("");
        jLabelPrioridade6.setText("");
        jLabelInstrucaoProcesso6.setText("");

    }
    
    
    public void arrumar(){
        atualizarTarefas();
        numtarefa.set(0, null);
        numtarefa.set(1, null);
        numtarefa.set(2, null);
        numtarefa.set(3, null);
        arrumaralocacao();
        atualizarthreadtextoatual();
        atualizarthreadtextoultimoprocesso();
        
        if (tarefas.size()>6) {
            jLabelTarefaExtra.setVisible(true);
        }
        else{
            jLabelTarefaExtra.setVisible(false);
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarProcessoThread1;
    private javax.swing.JButton jButtonAlterarProcessoThread2;
    private javax.swing.JButton jButtonAlterarProcessoThread3;
    private javax.swing.JButton jButtonAlterarProcessoThread4;
    private javax.swing.JButton jButtonIniciarProcessamento;
    private javax.swing.JLabel jLabelBorda1;
    private javax.swing.JLabel jLabelBorda10;
    private javax.swing.JLabel jLabelBorda2;
    private javax.swing.JLabel jLabelBorda3;
    private javax.swing.JLabel jLabelBorda4;
    private javax.swing.JLabel jLabelBorda5;
    private javax.swing.JLabel jLabelBorda6;
    private javax.swing.JLabel jLabelBorda7;
    private javax.swing.JLabel jLabelBorda8;
    private javax.swing.JLabel jLabelBorda9;
    private javax.swing.JLabel jLabelEndereçoMemoria0;
    private javax.swing.JLabel jLabelEndereçoMemoria1;
    private javax.swing.JLabel jLabelEndereçoMemoria2;
    private javax.swing.JLabel jLabelEndereçoMemoria3;
    private javax.swing.JLabel jLabelEndereçoMemoria4;
    private javax.swing.JLabel jLabelEndereçoMemoria5;
    private javax.swing.JLabel jLabelEndereçoMemoria6;
    private javax.swing.JLabel jLabelEndereçoMemoria7;
    private javax.swing.JLabel jLabelEndereçoMemoria8;
    private javax.swing.JLabel jLabelEndereçoMemoria9;
    private javax.swing.JLabel jLabelInstrucaoProcesso1;
    private javax.swing.JLabel jLabelInstrucaoProcesso2;
    private javax.swing.JLabel jLabelInstrucaoProcesso3;
    private javax.swing.JLabel jLabelInstrucaoProcesso4;
    private javax.swing.JLabel jLabelInstrucaoProcesso5;
    private javax.swing.JLabel jLabelInstrucaoProcesso6;
    private javax.swing.JLabel jLabelNomeProcesso1;
    private javax.swing.JLabel jLabelNomeProcesso2;
    private javax.swing.JLabel jLabelNomeProcesso3;
    private javax.swing.JLabel jLabelNomeProcesso4;
    private javax.swing.JLabel jLabelNomeProcesso5;
    private javax.swing.JLabel jLabelNomeProcesso6;
    private javax.swing.JLabel jLabelNomeThread1;
    private javax.swing.JLabel jLabelNomeThread10;
    private javax.swing.JLabel jLabelNomeThread2;
    private javax.swing.JLabel jLabelNomeThread3;
    private javax.swing.JLabel jLabelNomeThread4;
    private javax.swing.JLabel jLabelNomeThread5;
    private javax.swing.JLabel jLabelNomeThread6;
    private javax.swing.JLabel jLabelNomeThread7;
    private javax.swing.JLabel jLabelNomeThread8;
    private javax.swing.JLabel jLabelNomeThread9;
    private javax.swing.JLabel jLabelPrioridade1;
    private javax.swing.JLabel jLabelPrioridade2;
    private javax.swing.JLabel jLabelPrioridade3;
    private javax.swing.JLabel jLabelPrioridade4;
    private javax.swing.JLabel jLabelPrioridade5;
    private javax.swing.JLabel jLabelPrioridade6;
    private javax.swing.JLabel jLabelTarefaExtra;
    private javax.swing.JLabel jLabelTextoEnderecoMemoria1;
    private javax.swing.JLabel jLabelTextoEnderecoMemoria10;
    private javax.swing.JLabel jLabelTextoEnderecoMemoria2;
    private javax.swing.JLabel jLabelTextoEnderecoMemoria3;
    private javax.swing.JLabel jLabelTextoEnderecoMemoria4;
    private javax.swing.JLabel jLabelTextoEnderecoMemoria5;
    private javax.swing.JLabel jLabelTextoEnderecoMemoria6;
    private javax.swing.JLabel jLabelTextoEnderecoMemoria7;
    private javax.swing.JLabel jLabelTextoEnderecoMemoria8;
    private javax.swing.JLabel jLabelTextoEnderecoMemoria9;
    private javax.swing.JLabel jLabelTextoInstrucaoProcesso1;
    private javax.swing.JLabel jLabelTextoInstrucaoProcesso2;
    private javax.swing.JLabel jLabelTextoInstrucaoProcesso3;
    private javax.swing.JLabel jLabelTextoInstrucaoProcesso4;
    private javax.swing.JLabel jLabelTextoInstrucaoProcesso5;
    private javax.swing.JLabel jLabelTextoInstrucaoProcesso6;
    private javax.swing.JLabel jLabelTextoMemoria;
    private javax.swing.JLabel jLabelTextoNomeProcesso1;
    private javax.swing.JLabel jLabelTextoNomeProcesso2;
    private javax.swing.JLabel jLabelTextoNomeProcesso3;
    private javax.swing.JLabel jLabelTextoNomeProcesso4;
    private javax.swing.JLabel jLabelTextoNomeProcesso5;
    private javax.swing.JLabel jLabelTextoNomeProcesso6;
    private javax.swing.JLabel jLabelTextoPUltimoProcesso3;
    private javax.swing.JLabel jLabelTextoPUltimoProcesso4;
    private javax.swing.JLabel jLabelTextoPrioridade1;
    private javax.swing.JLabel jLabelTextoPrioridade2;
    private javax.swing.JLabel jLabelTextoPrioridade3;
    private javax.swing.JLabel jLabelTextoPrioridade4;
    private javax.swing.JLabel jLabelTextoPrioridade5;
    private javax.swing.JLabel jLabelTextoPrioridade6;
    private javax.swing.JLabel jLabelTextoProcessoAtual1;
    private javax.swing.JLabel jLabelTextoProcessoAtual2;
    private javax.swing.JLabel jLabelTextoProcessoAtual3;
    private javax.swing.JLabel jLabelTextoProcessoAtual4;
    private javax.swing.JLabel jLabelTextoUltimoProcesso1;
    private javax.swing.JLabel jLabelTextoUltimoProcesso2;
    private javax.swing.JLabel jLabelUltimoProcesso1;
    private javax.swing.JLabel jLabelUltimoProcesso2;
    private javax.swing.JLabel jLabelUltimoProcesso3;
    private javax.swing.JLabel jLabelUltimoProcesso4;
    private javax.swing.JLabel jLabelprocessoatual1;
    private javax.swing.JLabel jLabelprocessoatual2;
    private javax.swing.JLabel jLabelprocessoatual3;
    private javax.swing.JLabel jLabelprocessoatual4;
    // End of variables declaration//GEN-END:variables
}
