/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho.pkg2.jogo.de.so;

import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author vinic
 */
public class JframeTelaInicial extends javax.swing.JFrame {

    
    public JframeTelaInicial() {
        initComponents();
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButonNovoJogo = new javax.swing.JButton();
        JButonNovoJogo1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        JButonNovoJogo.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        JButonNovoJogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/botao verde.png"))); // NOI18N
        JButonNovoJogo.setText("Novo Jogo");
        JButonNovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButonNovoJogoActionPerformed(evt);
            }
        });
        getContentPane().add(JButonNovoJogo);
        JButonNovoJogo.setBounds(60, 30, 480, 130);

        JButonNovoJogo1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        JButonNovoJogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Botao azul.png"))); // NOI18N
        JButonNovoJogo1.setText("Instruções basicas");
        JButonNovoJogo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButonNovoJogo1ActionPerformed(evt);
            }
        });
        getContentPane().add(JButonNovoJogo1);
        JButonNovoJogo1.setBounds(60, 180, 480, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fundo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 620, 360);

        setSize(new java.awt.Dimension(624, 399));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JButonNovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButonNovoJogoActionPerformed
        JFrameTelaJogo telaJogo = new JFrameTelaJogo();
        
        telaJogo.setVisible(true);
    }//GEN-LAST:event_JButonNovoJogoActionPerformed

    private void JButonNovoJogo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButonNovoJogo1ActionPerformed
        JOptionPane.showMessageDialog(null, "O simulador funciona da forma que tem uma memoria simulada tem as tarefas e tem as threads.");
        JOptionPane.showMessageDialog(null, "A memoria simulada em resumo são 10 espaços de memoria onde que são implementados mutex para definir o aceso neles.");
        JOptionPane.showMessageDialog(null, "As tarefas contem um nome onde que e apenas para identificalas, uma prioridade onde que voce escolhe se acata ela ou não,\n e as operações onde que W e Wait que simula uma I/O ou uma operação de escrita ou algo do genero, L que acompanha com um numero \nonde que ele tranca o espaço da memoria representado no numero e o U serve para destravar.");
        JOptionPane.showMessageDialog(null, "Na parte superior do simulador tem a Thread onde voce pode definir qual tarefa ela ila executar em um tempo de execução.");
    }//GEN-LAST:event_JButonNovoJogo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeTelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeTelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButonNovoJogo;
    private javax.swing.JButton JButonNovoJogo1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
